routes/web.php
<?php

use App\Http\Controllers\Admin\HomePage\BannerController;
use App\Http\Controllers\Admin\HomePage\VenueController;
use App\Http\Controllers\Admin\HomePage\MessageController;
use App\Http\Controllers\Admin\Menu\MenuController;
use App\Http\Controllers\Admin\Menu\SubMenuController;
use App\Http\Controllers\Admin\Menu\PageController;
use App\Http\Controllers\Admin\DesignationController;
use App\Http\Controllers\Admin\DonortypeController;
use App\Http\Controllers\Admin\InviteeController;
use App\Http\Controllers\Admin\LeadershipTypeController;
use App\Http\Controllers\Admin\SponsorCategoryTypeController;
use App\Http\Controllers\Admin\LeftLogoController;
use App\Http\Controllers\Admin\RightLogoController;
use App\Http\Controllers\Admin\HomePage\ProgramController;
use App\Http\Controllers\Admin\HomePage\EventController;
use App\Http\Controllers\Admin\HomePage\ScheduleController;
use App\Http\Controllers\Admin\HomePage\DonorController;
use App\Http\Controllers\Admin\HomePage\VideoController;
use App\Http\Controllers\Admin\HomePage\MemberController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\RegistrationController;
use App\Http\Controllers\Admin\PaymenttypeController;
use App\Http\Controllers\Admin\SponsorCategoryController;
use App\Http\Controllers\Admin\PaymentController;
use App\Http\Controllers\Admin\BenefittypeController;

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'] );

//->middleware(['admin', 'auth'])
Route::prefix('admin')->group(function () {

    Route::resource('banner', BannerController::class);
    Route::put('banner-status-update', [BannerController::class ,'updateStatus']);

    Route::resource('venue', VenueController::class);

    Route::resource('message', MessageController::class);
    Route::put('message-status-update', [MessageController::class , 'updateStatus']);

    Route::resource('menu', MenuController::class);
    Route::put('menu-status-update', [MenuController::class, 'updateStatus']);

    Route::resource('submenu', SubMenuController::class);
    Route::put('submenu-status-update', [SubMenuController::class, 'updateStatus']);
    Route::get('get-submenu-with-menu/{id}/{edit?}', [SubMenuController::class, 'GetSubmenuWithMenu']);

    Route::resource('page', PageController::class);
    Route::put('page-status-update', [PageController::class, 'updateStatus']);

    Route::resource('donor', DonorController::class);
    Route::put('donor-status-update', [DonorController::class, 'updateStatus']);



    Route::resource('video', VideoController::class);
    Route::put('video-status-update', [VideoController::class, 'updateStatus']);

    Route::resource('member', MemberController::class);
    Route::put('member-status-update', [MemberController::class, 'updateStatus']);
    Route::get('assigne-roles/{id}', [MemberController::class, 'showAssigneRolesPage']);
    Route::post('store-assigne-roles', [MemberController::class, 'storeAssigneRolesPage']);

    // master routes
    Route::resource('designation', DesignationController::class);
    Route::put('designation-status-update', [DesignationController::class, 'updateStatus']);

    Route::resource('donortype', DonortypeController::class);
    Route::put('donortype-status-update', [DonortypeController::class, 'updateStatus']);

    Route::resource('invitee', InviteeController::class);
    Route::put('invitee-status-update', [InviteeController::class, 'updateStatus']);

    Route::resource('leadership-type', LeadershipTypeController::class);
    Route::put('leadership-type-status-update', [LeadershipTypeController::class, 'updateStatus']);

    Route::resource('sponsor-category-type', SponsorCategoryTypeController::class);
    Route::put('sponsor-category-type-status-update', [SponsorCategoryTypeController::class, 'updateStatus']);

    Route::resource('left-logo', LeftLogoController::class);
    Route::put('left-logo-status-update', [LeftLogoController::class, 'updateStatus']);
    Route::resource('right-logo', RightLogoController::class);
    Route::put('right-logo-status-update', [RightLogoController::class, 'updateStatus']);

    Route::resource('program', ProgramController::class);
    Route::put('program-status-update', [ProgramController::class, 'updateStatus']);

    Route::resource('event', EventController::class);
    Route::put('event-status-update', [EventController::class, 'updateStatus']);

    Route::resource('schedule', ScheduleController::class);

    Route::resource('sponsor-category', SponsorCategoryController::class);
    Route::put('sponsor-category-status-update', [SponsorCategoryController::class, 'updateStatus']);

    Route::resource('paymenttype', PaymenttypeController::class);
    Route::put('paymenttype-status-update', [PaymenttypeController::class, 'updateStatus']);

    Route::resource('benefittype', BenefittypeController::class);
    Route::put('benefittype-status-update', [BenefittypeController::class, 'updateStatus']);

    Route::get('registrations', [RegistrationController::class, 'showRegistrations']);
    Route::get('assigne-features/{id}', [RegistrationController::class, 'showAssigneFeatures']);
    Route::put('assigne-features-update', [RegistrationController::class, 'updateAssigneFeatures']);

});

Route::get('reload-captcha', [HomeController::class, 'reloadCaptcha']);

Route::get('payment', [PaymentController::class, 'index']);
Route::get('payment/status', [PaymentController::class, 'status'])->name('payment.status');
Route::get('padingpayment/status', [PaymentController::class, 'pendingstatus'])->name('pendingpayment.status');
Route::get('print-ticket', [RegistrationController::class, 'printTicket']);

Route::get('/admin', function () {
    return view('admin/dashboard');
});
Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');


require __DIR__.'/auth.php';

Route::middleware(['auth'])->group(function () {
    Route::get('viewfeatuees', [RegistrationController::class, 'viewFeatures'])->name('viewfeatures');
    Route::get('paymenthistory', [RegistrationController::class, 'PaymentHistory'])->name('PaymentHistory');
    Route::get('pay-pending-amount', [PaymentController::class, 'payPendingAmount'])->name('pay-pending-amount');
    Route::post('pay-pending-amount', [PaymentController::class, 'storePayPendingAmount'])->name('pay-pending-amount');
    Route::get('myaccount', [RegistrationController::class, 'myaccount'])->name('myaccount');
    Route::get('bookticket', [RegistrationController::class, 'ShowRegistrationForm'])->name('bookticket');
});


Route::post('bookticketstore', [RegistrationController::class, 'RegesterUserStore']);

Route::get('registration-page-content-update', [RegistrationController::class, 'RegistrationPageContentedit'])->name('registration-page-content-update');
Route::patch('registration-page-content-update', [RegistrationController::class, 'RegistrationPageContentUpdate'])->name('registration-page-content-update');

Route::get('message_content/{id}', [HomeController::class, 'messageContent']);
Route::get('programs/{id}', [HomeController::class, 'programDetailsPage']);
Route::get('event-schedule/{id}', [HomeController::class, 'eventSchedule']);
Route::get('show-all-videos', [HomeController::class, 'showAllVideos']);
Route::get('more-donor-details/{id}', [HomeController::class, 'moreDonerDetails']);
Route::get('more-leadership-details/{id}', [HomeController::class, 'moreLeadershipDetails']);
Route::get('more-invitee-details/{id}', [HomeController::class, 'moreInviteeDetails']);
Route::get('show-events-on-calander', [HomeController::class, 'showEventsOnCalander']);


Route::get('api/get-schedule-on-date/{id}', [ScheduleController::class, 'getScheduleDatails']);
Route::get('api/get-donor-with-typeid/{id}', [HomeController::class, 'getDonorsWithTypeId']);
Route::get('api/get-leadership-with-typeid/{id}', [HomeController::class, 'getLeadershipsWithTypeId']);
Route::get('api/get-invitee-with-typeid/{id}', [HomeController::class, 'getinviteeWithTypeId']);
Route::get('api/get-invitee-with-typeid/{id}', [HomeController::class, 'getinviteeWithTypeId']);

Route::get('api/get-events-in-date', [HomeController::class, 'geteventsIndates']);
Route::get('api/get-details', [RegistrationController::class, 'getdetailsfromNriva']);

Route::get('{slug}', [HomeController::class, 'dinamicPage']);

app/Models/Admin/Menu.php
<?php

namespace App\Models\Admin;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Menu extends Model
{
    use HasFactory;
    protected $fillable = ['name','slug', 'parent_id', 'page_content'];

    public function submenus()
    {
        return $this->HasMany(Menu::class, 'parent_id');
    }

    public function menu()
    {
        return $this->belongsTo(Menu::class, 'parent_id');
    }
}

app/Http/Controllers/Admin/Menu/MenuController.php
<?php

namespace App\Http\Controllers\Admin\Menu;

use App\Http\Controllers\Controller;
use App\Models\Admin\Menu;
use Illuminate\Http\Request;

class MenuController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $menus = Menu::withCount('submenus')->where('parent_id',0)->get();
        return view('admin.ContentMangement.Menu.viewmenu', compact('menus'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.ContentMangement.Menu.addmenu');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       
        $rules = [
            'name' => ['required',],
        ];
       
        if($request->has('pageType')){
           
            $rules1=[
                'slug' => ['required'],
            ];

            $rules= array_merge($rules, $rules1);
        }

        $request->validate($rules);

        if (!$request->has('pageType')) {
            $request= $request->only('name');
        }else{
            $request= $request->all();
        }
         Menu::create($request);
  
        return redirect()
            ->route('menu.index')
            ->with('message-suc', 'Menu Added');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Admin\Menu  $menu
     * @return \Illuminate\Http\Response
     */
    public function show(Menu $menu)
    {
      
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Admin\Menu  $menu
     * @return \Illuminate\Http\Response
     */
    public function edit(Menu $menu)
    {
        return view('admin.ContentMangement.Menu.editmenu', compact('menu'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Admin\Menu  $menu
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Menu $menu)
    {
        if (!$request->has('pageType')) {
            $request = [
               'name'=> $request->name,
               'slug'=> null, 
            ];
        } else {
            $request = $request->only('name', 'slug');
        }
        
        Menu::where("id", $menu->id)
            ->update($request);

        return redirect()
            ->route('menu.index')
            ->with('message-suc', 'updated');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Admin\Menu  $menu
     * @return \Illuminate\Http\Response
     */
    public function destroy(Menu $menu)
    {
        $menu = Menu::find($menu->id);
        return $menu->delete();
    }

    public function updateStatus(Request $request)
    {
        return Menu::where('id', $request->id)->update(['status' => $request->status]);
    }
}

app/Http/Controllers/Admin/Menu/PageController.php
<?php

namespace App\Http\Controllers\Admin\Menu;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Admin\Menu;

class PageController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $pages = Menu::with('menu')
                    ->where('parent_id','!=',0)
                    ->where('page_content','!=',null)
                    ->get();
        return view('admin.ContentMangement.Page.viewpage', compact('pages'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $menus = Menu::where('parent_id', 0)->where('slug',null)->get();
       return view('admin.ContentMangement.Page.addpage', compact('menus'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = [
            'id' => ['required'],
            'parent_id' => ['required'],
            'page_content' => ['required'],
        ];

        $request->validate($rules);
        Menu::where('id', $request->id)->update([
            'page_content' => $request->page_content
        ]);

        return redirect()
            ->route('page.index')
            ->with('message-suc', 'Page Content Added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $page=Menu::find($id);
        $menus = Menu::where('parent_id', 0)->where('slug', null)->get();
        $submenus = Menu::where('parent_id', $page->parent_id )
                    ->Where('slug', null)
                    ->orWhere('id', $page->id)
                    ->get();
        return view('admin.ContentMangement.Page.editpage', compact('page', 'menus', 'submenus'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $rules = [
            'id' => ['required'],
            'parent_id' => ['required'],
            'page_content' => ['required'],
        ];
        $request->validate($rules);

        Menu::where('id', $request->id)->update([
            'page_content' => $request->page_content
        ]);

        return redirect()
            ->route('page.index')
            ->with('message-suc', 'updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Menu::where('id', $id)->update([
            'page_content' =>null
        ]);
        return 1;
    }

    public function updateStatus(Request $request)
    {
        return Menu::where('id', $request->id)->update(['status' => $request->status]);
    }
}

resources/views/admin/ContentMangement/Menu/addmenu.blade.php
@extends('layouts.admin.base')
@section('content')


<div class="page-header">
    <div class="row">
        <div class="col-9 col-sm-6 my-auto">
            <h5 class="page-title mb-0">Add Menu</h5>
        </div>
        <div class="col-3 col-sm-6 col-md-6 my-auto">
            <div class="float-right">
                <a href="{{route('menu.create')}}" data-toggle="tooltip" title="" class="btn back-btn" data-original-title="Cancel"><i class="fa fa-reply"></i></a>
            </div>
        </div>
    </div>
</div>

<!-- /Page Header -->

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <form action="{{route('menu.store')}}" method="post" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group row">
                        <label class="col-form-label col-md-4 my-auto">Menu Name<span class="mandatory">*</span></label>
                        <div class="col-md-8 my-auto">
                            <input type="text" class="form-control" name="name" placeholder="Menu Name">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-form-label col-md-4 my-auto">Menu Type<span class="mandatory">*</span></label>
                        <div class="col-md-8 my-auto">
                            <div class="form-check">
                                <input class="form-check-input  slug-checkbox" type="checkbox" value="yes" name="pageType">
                                <label class="form-check-label" for="defaultCheck1">
                                    Check if Menu Redricts to a page
                                </label>
                            </div>
                        </div>
                    </div>
                        <div class="form-group row slug-field" style="display:none">
                            <label class="col-form-label col-md-4 my-auto ">Slug Name<span class="mandatory">*</span></label>
                            <div class="col-md-8 my-auto">
                                <input type="text" class="form-control " name="slug" placeholder="Slug">
                            </div>
                        </div>



                    <div class="text-right">
                        <input class="btn btn-primary" type="submit" value="Submit">
                    </div>
            </div>
            </form>
        </div>
    </div>
</div>
</div>


@section('javascript')
<script>
    $(".slug-checkbox").change(function() {
        if (IsCheckBoxChecked(this)) {
            $('.slug-field').show()
        } else {
            $('.slug-field').hide()
        }
    })
</script>

@endsection


@endsection

resources/views/admin/ContentMangement/Menu/editmenu.blade.php
@extends('layouts.admin.base')
@section('content')


<div class="page-header">
    <div class="row">
        <div class="col-9 col-sm-6 my-auto">
            <h5 class="page-title mb-0">Edit Menu</h5>
        </div>
        <div class="col-3 col-sm-6 col-md-6 my-auto">
            <div class="float-right">
                <a href="{{ url()->previous() }}" data-toggle="tooltip" title="" class="btn back-btn" data-original-title="Cancel"><i class="fa fa-reply"></i></a>
            </div>
        </div>
    </div>
</div>

<!-- /Page Header -->

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <form action="{{route('menu.update', $menu->id )}}" method="post" enctype="multipart/form-data">
                    @csrf
                    {{ method_field('PATCH') }}
                   
                     <label class="col-form-label col-md-4 my-auto">Menu Name<span class="mandatory">*</span></label>
                        <div class="col-md-8 my-auto">
                            <input type="text" class="form-control" value="{{$menu->name}}" name="name" placeholder="Menu Name">
                        </div>

                        <label class="col-form-label col-md-4 my-auto">Menu Type<span class="mandatory">*</span></label>
                        <div class="col-md-8 my-auto">
                            <div class="form-check">
                                <input class="form-check-input  slug-checkbox" {{$menu->slug!=null ? 'checked' : "" }} type="checkbox" value="yes" name="pageType">
                                <label class="form-check-label" for="defaultCheck1">
                                    Check if Menu Redricts to a page
                                </label>
                            </div>
                        </div>

                              <div class="slug-field" style="display:none">
                        <label class="col-form-label col-md-4 my-auto ">Slug Name<span class="mandatory">*</span></label>
                        <div class=" my-auto">
                            <input type="text" class="form-control" name="slug" value="{{$menu->slug}}" placeholder="Slug">
                        </div>
                       </div> 
                  
                    <div class="text-right">
                        <input class="btn btn-primary" type="submit" name="submit" value="Submit">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


@section('javascript')
<script>
$(document).ready(function () {
    if('{{$menu->slug}}' != "" ){
        $('.slug-field').show()
    }else{
        $('.slug-field').hide()
    }

$(".slug-checkbox").change(function () {
    if(IsCheckBoxChecked(this)){
        $('.slug-field').show()
    }else{
        $('.slug-field').hide()
    }
}) 
})


</script>

@endsection

@endsection

resources/views/admin/ContentMangement/Menu/viewmenu.blade.php
@extends('layouts.admin.base')
@section('content')


<!-- Page Header -->

<div class="page-header">
    <div class="row">
        <div class="col-9 col-sm-6 my-auto">
            <h5 class="page-title mb-0">Menu Managment</h5>
        </div>
        <div class="col-3 col-sm-6 col-md-6 my-auto">
            <div class="float-right">
                <a href="{{route('menu.create')}}" title="" class="add-new-btn btn" data-original-title="Add New"><i class="fa fa-plus"></i></a>
            </div>
        </div>
    </div>
</div>

<!-- /Page Header -->

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="datatable table table-hover table-center mb-0">
                        <thead>
                            <tr>
                                <th>S.No</th>
                                <th>Menu Name</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse($menus as $menu )
                            <tr>
                                <td>{{$loop->iteration}}</td>
                                <td>{{$menu->name}}</td>
                                <td>
                                    <a href="{{route('menu.edit', $menu->id)}}" class="btn btn-sm btn-success text-white my-1 mx-1">Edit</a>
                                    <button {{$menu->submenus_count>0 ? 'disabled' : "" }} data-id={{$menu->id}} data-url='{{ env("APP_URL") }}/admin/menu/{{$menu->id}}' class="btn btn-sm btn-success my-1 mx-1  delete-btn">Delete</button>
                                    <a href="#" data-url="{{ env("APP_URL") }}/admin/menu-status-update" class="btn btn-sm btn-success text-white my-1 mx-1 status-btn" data-id={{$menu->id}}>{{ $menu->status=='1' ?  'Active': 'InActive' }}</a>
                                </td>
                            </tr>

                            @empty
                            <p>No menu To Show</p>
                            @endforelse

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection